name: Checks

on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - master

  pull_request:
    branches:
      - "main"
      - "master"
      - "dev"
    paths-ignore:
      - "**/README.md"
      - "**/Makefile"
      - "**/.env.**"
      - "**/docker-compose.*.yml"
      - "**/.vscode"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
